{
 "title": "Taxi Monitoring Project",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-02-27T00:00:00.000Z" },
 "panels": [
  {
   "title": "share_missing_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT timestamp AS \"time\", share_missing_values FROM dummy_metrics ORDER BY 1"
    }
   ]
  },
  {
   "title": "num_drifted_columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT timestamp AS \"time\", num_drifted_columns FROM dummy_metrics ORDER BY 1"
    }
   ]
  },
  {
   "title": "prediction_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  prediction_drift\r\n  \r\nFROM dummy_metrics\r\nORDER BY 1"
    }
   ]
  }
 ]
}